<a href="https://colab.research.google.com/github/arfmatos/time-series/blob/main/basico_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [2]:
# Criando um array NumPy
a = np.array([1, 2, 3])              # array 1D
b = np.array([[1, 2, 3], [4, 5, 6]])# array 2D
c = np.zeros((2,2))                  # array de zeros 2x2
d = np.ones((3,3))                   # array de uns 3x3
e = np.random.rand(2,2)              # array aleatório 2x2



In [7]:
# Operações básicas
print("a + b =", a + b)                               # Soma elemento por elemento
print("np.add(a, b) =", np.add(a, b))                        # Soma elemento por elemento (outra forma)
print("a - b =", a - b)                               # Subtrai elemento por elemento
print("np.subtract(a, b) =", np.subtract(a, b))                   # Subtrai elemento por elemento (outra forma)
print("a * b =", a * b)                               # Multiplica elemento por elemento
print("np.multiply(a, b) =", np.multiply(a, b))                   # Multiplica elemento por elemento (outra forma)
print("np.dot(a, b) =", np.dot(b, a))                        # Produto de matrizes (dot product)
print("a.T =", a.T)                                 # Transposta




a + b = [[2 4 6]
 [5 7 9]]
np.add(a, b) = [[2 4 6]
 [5 7 9]]
a - b = [[ 0  0  0]
 [-3 -3 -3]]
np.subtract(a, b) = [[ 0  0  0]
 [-3 -3 -3]]
a * b = [[ 1  4  9]
 [ 4 10 18]]
np.multiply(a, b) = [[ 1  4  9]
 [ 4 10 18]]
np.dot(a, b) = [14 32]
a.T = [1 2 3]


In [8]:
# Funções estatísticas
print("np.mean(a) =", np.mean(a))                          # Média
print("np.median(a) =", np.median(a))                      # Mediana
print("np.std(a) =", np.std(a))                            # Desvio padrão
print("np.var(a) =", np.var(a))                            # Variância




np.mean(a) = 2.0
np.median(a) = 2.0
np.std(a) = 0.816496580927726
np.var(a) = 0.6666666666666666


In [9]:
# Indexação e fatiamento
print("a[0] =", a[0])                                 # Retorna o primeiro elemento de a
print("b[0, 1] =", b[0, 1])                                # Retorna o elemento na linha 0 e coluna 1 de b
print("c[1, :] =", c[1, :])                                # Retorna a segunda linha inteira de c
print("d[:, 2] =", d[:, 2])                                # Retorna a terceira coluna inteira de d
print("b[0:2, 1:3] =", b[0:2, 1:3])                          # Retorna uma matriz 2x2 com os elementos na primeira e segunda linha e segunda e terceira coluna de b



a[0] = 1
b[0, 1] = 2
c[1, :] = [0. 0.]
d[:, 2] = [1. 1. 1.]
b[0:2, 1:3] = [[2 3]
 [5 6]]


In [10]:
# Alterando o formato de um array
a.shape = (3, 1)                                        # Muda a forma de a para 3 linhas e 1 coluna
print("np.reshape(a, (3, 1)) =", np.reshape(a, (3, 1)))           # Muda a forma de a para 3 linhas e 1 coluna (outra forma)
print("a.ravel() =", a.ravel())                           # Transforma a em um vetor unidimensional



np.reshape(a, (3, 1)) = [[1]
 [2]
 [3]]
a.ravel() = [1 2 3]


In [14]:
# Concatenação de arrays
print("np.concatenate((b, d), axis=0) =", np.concatenate((b, d), axis=0)) # Concatena a e b ao longo do eixo 0 (verticalmente)

np.concatenate((b, d), axis=0) = [[1. 2. 3.]
 [4. 5. 6.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
